// <auto-generated />
namespace puck.core.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class indexes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(indexes));
        
        string IMigrationMetadata.Id
        {
            get { return "201307080849396_indexes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
